using System.Globalization;
using System.Net;
using System.Text;

namespace Skald.Recorder;

public static class SessionReportWriter
{
    public static async Task WriteHtmlAsync(SessionDocument document, string filePath, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(document);
        ArgumentException.ThrowIfNullOrWhiteSpace(filePath);

        var samples = document.Samples;
        var peakCpu = samples.Where(sample => sample.Cpu.Availability.IsSupported).Select(sample => sample.Cpu.UtilizationPercent).DefaultIfEmpty().Max();
        var peakMemory = samples.Where(sample => sample.Memory.Availability.IsSupported).Select(sample => sample.Memory.UsedPercent).DefaultIfEmpty().Max();
        var peakDisk = samples.Where(sample => sample.Disk.Availability.IsSupported).Select(sample => sample.Disk.ActiveTimePercent).DefaultIfEmpty().Max();
        var primaryProcess = samples.SelectMany(sample => sample.Processes).GroupBy(process => process.Name, StringComparer.OrdinalIgnoreCase).Select(group => new { Name = group.Key, Cpu = group.Max(process => process.CpuPercent) }).OrderByDescending(item => item.Cpu).FirstOrDefault();
        var power = PowerSessionSummary.From(document);

        var html = new StringBuilder();
        html.AppendLine("<!doctype html><html><head><meta charset=\"utf-8\"><title>Skald Session Report</title>");
        html.AppendLine("<style>body{font:15px system-ui,sans-serif;background:#101114;color:#e9eaee;max-width:980px;margin:40px auto;padding:0 24px}h1{font-size:32px}h2{margin-top:32px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.card{background:#1b1d22;border-radius:8px;padding:18px}.muted{color:#a5a7b0}table{width:100%;border-collapse:collapse;background:#1b1d22}td,th{text-align:left;padding:10px;border-bottom:1px solid #30333a}</style></head><body>");
        html.AppendLine(CultureInfo.InvariantCulture, $"<h1>Skald Session Report</h1><p class=\"muted\">{Encode(document.Metadata.MachineName)} · {document.Metadata.StartedAt.ToLocalTime().ToString("yyyy-MM-dd HH:mm:ss", CultureInfo.InvariantCulture)} to {document.Metadata.EndedAt.ToLocalTime().ToString("yyyy-MM-dd HH:mm:ss", CultureInfo.InvariantCulture)}</p>");
        html.AppendLine("<div class=\"grid\">");
        AppendCard(html, "Samples", samples.Count.ToString(CultureInfo.InvariantCulture));
        AppendCard(html, "Peak CPU", $"{peakCpu:F1}%");
        AppendCard(html, "Peak memory", $"{peakMemory:F1}%");
        AppendCard(html, "Peak disk activity", $"{peakDisk:F1}%");
        AppendCard(html, "Events", document.Events.Count.ToString(CultureInfo.InvariantCulture));
        AppendCard(html, "Top process peak", primaryProcess is null ? "Unavailable" : $"{Encode(primaryProcess.Name)} ({primaryProcess.Cpu:F1}% CPU)");
        AppendCard(html, "Average battery draw", power.AverageDischargeWatts is { } draw ? $"{draw:F1} W" : "Unavailable");
        AppendCard(html, "Peak battery draw", power.PeakDischargeWatts is { } peak ? $"{peak:F1} W" : "Unavailable");
        AppendCard(html, "Estimated battery energy used", power.EstimatedBatteryEnergyWh is { } energy ? $"{energy:F2} Wh" : "Unavailable");
        AppendCard(html, "Battery draw coverage", $"{power.RunCoveragePercent:F0}% of run");
        AppendCard(html, "Runtime from full charge at average draw", power.FullChargeRuntimeHours is { } hours ? $"{hours:F1} h" : "Unavailable");
        html.AppendLine("</div><h2>Events</h2><table><thead><tr><th>Time</th><th>Type</th><th>Details</th></tr></thead><tbody>");
        foreach (var sessionEvent in document.Events.OrderBy(item => item.Timestamp))
        {
            html.AppendLine(CultureInfo.InvariantCulture, $"<tr><td>{sessionEvent.Timestamp.ToLocalTime().ToString("HH:mm:ss", CultureInfo.InvariantCulture)}</td><td>{Encode(sessionEvent.Type.ToString())}</td><td>{Encode(sessionEvent.Note ?? string.Empty)}</td></tr>");
        }

        html.AppendLine("</tbody></table><p class=\"muted\">Generated by Skald. Measurements are shown only when the collector reported them as available.</p></body></html>");
        var directory = Path.GetDirectoryName(filePath);
        if (!string.IsNullOrEmpty(directory)) Directory.CreateDirectory(directory);
        await File.WriteAllTextAsync(filePath, html.ToString(), Encoding.UTF8, cancellationToken);
    }

    private static void AppendCard(StringBuilder html, string label, string value) => html.AppendLine(CultureInfo.InvariantCulture, $"<div class=\"card\"><div class=\"muted\">{Encode(label)}</div><strong>{value}</strong></div>");

    private static string Encode(string value) => WebUtility.HtmlEncode(value);
}
